type AppId = number

interface SteamClient {
  Apps: Apps,
  Browser: any,
  BrowserView: any,
  ClientNotifications: any,
  Cloud: any,
  Console: any,
  Downloads: any,
  FamilySharing: any,
  FriendSettings: any,
  Friends: any,
  GameSessions: any,
  Input: any,
  InstallFolder: any,
  Installs: any,
  MachineStorage: any,
  Messaging: any,
  Notifications: Notifications,
  OpenVR: any,
  Overlay: any,
  Parental: any,
  RegisterIFrameNavigatedCallback: any,
  RemotePlay: any,
  RoamingStorage: any,
  Screenshots: any,
  Settings: any,
  SharedConnection: any,
  Stats: any,
  Storage: any,
  Streaming: any,
  System: any,
  UI: any,
  URL: any,
  Updates: any,
  User: User,
  WebChat: any,
  Window: any
}
